service: daily-digest
# app and org for use with dashboard.serverless.com
app: daily-digest-app
org: samtgarson
useDotenv: true

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  region: eu-west-2
  environment:
    MAILER_RECIPIENT: ${env:MAILER_RECIPIENT}
    MAILER_SENDER: ${env:MAILER_SENDER}
    OUTPUT_DIR: /tmp/digest-delivery
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_KEY}


plugins:
  - serverless-plugin-ncc
  - serverless-offline

package:
  individually: true

functions:
  saveArticle:
    handler: functions/save.handler
    events:
      - httpApi:
          path: /articles
          method: POST
  deliverDigest:
    handler: functions/deliver.handler
    events:
      - schedule: cron(0 0 * * ? *)

custom:
  ncc:
    minify: true
    externals: ["aws-sdk"]
