import type { Article } from 'types/digest'
import { Digest } from '../../lib/digest'

const article1: Article = {
  id: '1',
  created_at:  new Date(),
  content: 'content 1',
  title: 'title 1',
  author: 'author 1'
}

const article2: Article = {
  id: '2',
  created_at:  new Date(),
  content: 'content 2',
  title: 'title 2'
}

describe('digest', () => {
  const date = {
    toLocaleString: jest.fn(() => 'locale string')
  } as unknown as Date

  const digest = new Digest([article1, article2], date)

  it('has a title', () => {
    expect(digest.title).toEqual('Digest (locale string)')
  })

  it('has a table of contents', () => {
    expect(digest.html).toEqual(
`<header>
<h1>Digest (locale string)</h1>
<p style="margin: 40px 0">You've got 2 articles to read!</p>
<ol>
<li><a href="#1">title 1</a><em>—author 1</em></li>
<li><a href="#2">title 2</a><em>—undefined</em></li>
</ol>
</header>
<h1 id="1">title 1</h1>
<p style="color: #444; margin-bottom: 30px">By author 1</p>
content 1
<h1 id="2">title 2</h1>
content 2

<footer style="color: #444;">
<p>Generated by <a href="samgarson.com">Digest Bot</a></p>
</footer>`
      )
  })
})
