name: build
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
          cache: 'npm'
      - run: npm install
      - run: npm run lint
      - run: npm run test

  build-action:
    name: Build Action
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: delivery/Dockerfile
          context: .
          push: true
          tags: |
            ghcr.io/samtgarson/digest-delivery:latest
            ghcr.io/samtgarson/digest-delivery:${{ github.sha }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/samtgarson/digest-delivery:latest
          cache-to: type=registry,ref=ghcr.io/samtgarson/digest-delivery:latest
