name: deliver
on:
  workflow_dispatch:
    debug:
      description: Show debug logs
      required: false
      default: false
  schedule:
    - cron:  '0 0 * * *'
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Deliver digests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run delivery
        uses: ./.github/actions/deliver
        env:
          MAILER_RECIPIENT: ${{ secrets.MAILER_RECIPIENT }}
          MAILER_SENDER: ${{ secrets.MAILER_SENDER }}
          OUTPUT_DIR: /tmp/digest-delivery
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_COVERS_BUCKET_NAME: ${{ secrets.S3_COVERS_BUCKET_NAME }}
          DEBUG: ${{ github.event.inputs.debug == 'true' }}

